# Generated by Django 5.1.3 on 2024-11-08 18:56

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voicemail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, verbose_name="phone number"
                    ),
                ),
                ("location", models.CharField(default="Unknown", max_length=256)),
                ("duration", models.DurationField(default=datetime.timedelta(0), verbose_name="duration")),
                ("file", models.FileField(upload_to="voicemails/", verbose_name="audio file")),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "get_latest_by": "created_at",
            },
        ),
    ]
