services:
  app:
    restart: always
    volumes:
      - ./.env:/.env:ro
      - ./serve:/serve
    depends_on:
      - db
    build:
      context: .
      args:
        DEBUG: "${DEBUG:-0}"

  nginx:
    image: ghcr.io/dtcooper/nginx-certbot-jinja:5.4.0-nginx1.27.2
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx.conf.jinja:/etc/nginx/templates/site.conf.jinja:ro
      - ./serve:/serve:ro
      - nginx_secrets:/etc/letsencrypt
    environment:
      DEBUG: "${DEBUG:-0}"
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
      DOMAIN_NAME: "${DOMAIN_NAME}"
    ports:
      - 80:80
      - 443:443

  db:
    restart: always
    image: pgautoupgrade/pgautoupgrade:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  nginx_secrets: {}
  postgres_data: {}
