version: '3'
services:
  app:
    image: calls-app
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:10.9
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
