version: '3'
services:
  app:
    image: calls-app
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: calls-db
    build:
      context: docker
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
