API_PASSWORD = 'hackme'

SQLALCHEMY_DATABASE_URI = 'postgresql://localhost/bmir_calls'
SQLALCHEMY_TRACK_MODIFICATIONS = False

TWILIO_ACCOUNT_SID = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
TWILIO_AUTH_TOKEN = 'hackme'
